import type { Metadata } from "next";
import i18nConfig from "@/i18nConfig";
import { ReactNode } from "react";
import { dir } from "i18next";
import { notFound } from "next/navigation";
import { ThemeProvider } from "@/context/ThemeContext"; // Import your ThemeProvider
import "@/styles/global.css";
import StyledComponentsRegistry from "@/lib/registry";
import TranslationsProvider from "@/components/translationProvider/TranslationProvider";
import { I18nPages } from "@/constants/constants";
import initTranslations from "@/utils/i18n";
import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  if (!i18nConfig.locales.includes(locale)) {
    notFound();
  }

  const i18nNamespaces = [I18nPages.Dashboard, I18nPages.About];
  const { resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <html lang={locale} dir={dir(locale)}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <TranslationsProvider
              namespaces={i18nNamespaces}
              locale={locale}
              resources={resources}
            >
              <div className="container">
                <Navbar />
                {children}
              </div>
            </TranslationsProvider>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
